version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'monthly'
    groups:
      angular:
        patterns:
          - '@angular/*'
      npm-dependencies:
        patterns:
          - '*'
        exclude-patterns:
          - '@angular/*'
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'monthly'
