name: Lint
on:
  pull_request:
jobs:
  prettier:
    name: Prettier Check Codebase
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v6
        with:
          cache: 'npm'
          node-version: '24'
      - run: npm ci
      - run: npm run prettier:check
  lint:
    name: Lint Codebase
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v6
        with:
          cache: 'npm'
          node-version: '24'
      - run: npm ci
      - run: npm run lint
