name: Release
on:
  push:
    tags:
      - 'v*'
jobs:
  deploy:
    name: Create GitHub Release
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - uses: ncipollo/release-action@v1
        with:
          artifacts: 'CHANGELOG.md,LICENSE,README.md'
          generateReleaseNotes: true
          token: ${{ secrets.GITHUB_TOKEN }}
